steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['functions', 'deploy', 'pubsub_to_bigquery', 
  '--source', './cloudfunction/', 
  '--gen2',
  '--runtime', 'python312', 
  '--region', 'us-central1', 
  '--trigger-topic', 'activities', 
  '--timeout', '60s',
  '--max-instances', '10',
  '--memory', '256MB']
options:
  logging: CLOUD_LOGGING_ONLY
